### ISSUE TITLE
[📚] EEA Consent GDPR - Must not display ads if consent denied?!

### ISSUE THREAD

**Issue by VictorioMolina** [invertase/react-native-google-mobile-ads#274]
### Documentation Feedback

Hey! I am launching a free App soon, and I will have downloads from the EEA. I have implemented the EEA info consent as indicated in your docs.

In react native firebase docs, I have read the [following](https://rnfb-docs.netlify.app/admob/european-user-consent#forwarding-the-consent-status-to-ads):

> __If the user is within the EEA and has not given consent, do not display AdMob ads (even non-personalized).__

So... if the user in the EEA denies the consent, I understand that AdMob will not show personalized ads to him? But now showing non-personalized ads?! WTF... is this some kind of AdBlock? Also, in the Apple Store guidelines, it clearly says that we can't force users to accept the consent.

Can we use the user choices returned by `AdsConsent. getUserChoices()`, to dynamically modify the property `requestNonPersonalizedAdsOnly` passed to the `createForAdRequest()` method?

I mean, something like this:

```
const interstitial = InterstitialAd.createForAdRequest(adUnitId, {
  ...ADS_REQUEST_OPTIONS,
  requestNonPersonalizedAdsOnly: !userChoices.selectPersonalisedAds,
});
```

Here is my code:

1. _config.js_:

```
export const TEST_DEVICE_ID = "EMULATOR";

export const INFO_REQUEST_CONFIGURATION = {
  tagForUnderAgeOfConsent: true,
  testDeviceIdentifiers: [TEST_DEVICE_ID],
  // Always ensure debug information is removed for production apps!
  ...__DEV__ && { debugGeography: AdsConsentDebugGeography.EEA },
};

export const ADS_REQUEST_CONFIGURATION = {
  maxAdContentRating: MaxAdContentRating.T,
  tagForChildDirectedTreatment: false,
  tagForUnderAgeOfConsent: true,
  testDeviceIdentifiers: [TEST_DEVICE_ID],
};

export const ADS_REQUEST_OPTIONS = {
  requestNonPersonalizedAdsOnly: false,
  keywords: [
    ...
  ],
};
```

2. _AdMobContext.jsx_:

```
...

export function AdMobProvider({ children }) {
  const requestEEAConsent = async () => {
    const consentInfo = await AdsConsent.requestInfoUpdate(INFO_REQUEST_CONFIGURATION);

    if (
      consentInfo.isConsentFormAvailable &&
      consentInfo.status === AdsConsentStatus.REQUIRED
    ) {
      const { status } = await AdsConsent.showForm();

      consentInfo.status = status;
    }

    console.log({ consentInfo });

    return consentInfo;
  };

  const initializeAdmob = async () => {
    // Request the respective consent to users in the EEA
    await requestEEAConsent();

    // Configure the ads requests
    await mobileAds().setRequestConfiguration(ADS_REQUEST_CONFIGURATION);

    // Initialize the AdMob service
    await mobileAds().initialize();
  };

   useEffect(() => {
    initializeAdmob();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);
  
   ...
}

```

__When I am testing this on my iOS simulator (without modifying the `requestNonPersonalizedAdsOnly` field (its always `false`)), even if I do not consent AdMob, ads are displayed. WHY?__

**Comment by mikehardy** [comment]
react-native-firebase has very little relation to this module anymore. Firebase dropped admob 2.5 *years* ago.

So, I would not use the old docs, I am not sure I can just delete them but if I could I would, everything in the consent space moves rapidly and I would simply not trust old documentation. Don't use the old docs.

Further to that thought that you should only consult up to date docs that are authoritative, I would not trust what I think either. 

I'm not an advertising professional nor do I even use this module currently! Just doing my best to maintain it.

What you need to do is consult the upstream docs and follow them - 

- https://docs.page/invertase/react-native-google-mobile-ads#european-user-consent (where we point upstream)
  - https://developers.google.com/admob/ump/ios/quick-start
  - https://developers.google.com/admob/ump/android/quick-start

And a page with some examples showing how to use the UMP library which this module does wrap and export for you: 
https://docs.page/invertase/react-native-google-mobile-ads/european-user-consent

When in doubt, the upstream admob/ump docs are the authoritative source, though our EU user consent page attempts to help. If you compare the two and our page has any errors please :pray: hit the edit button and propose a PR to help keep it in line

**Comment by mikehardy** [comment]
You can do ATT separate if it's from the issue you linked, using a react-native-permissions and (I think this is important...) A real device

That may help untangle it (separate phases for att and ad consent) and maybe fix it (real device)

**Comment by VictorioMolina** [comment]
For people coming here in the future, here some of the questions I have had to solve when implementing the EEA consent with this library.

---

Q1. What happens after granting the consent? Do we need to dynamically change the ad request options to serve non personalized ads? More about this [here](https://github.com/birgernass/react-native-ad-consent/issues/23#issuecomment-1320232395).
A1. https://developers.google.com/admob/ump/android/quick-start#forward-consent It seems that, for react-native-google-mobile-ads, because of [this](https://github.com/invertase/react-native-google-mobile-ads/blob/8bbfc058b20f599acc3fd91d0145c4f974bf2d09/ios/RNGoogleMobileAds/RNGoogleMobileAdsCommon.m#L54) line, we need to dynamically change the `requestNonPersonalizedAdsOnly` value. This is not automatically handled by AdMob.

---

Q2. Can I show ads non-personalized ads if the user doesn't consent the _'Store or access information on a device'_ statement?
A2. A GDPR expert and lawyer has told me the following: 
> **_Even if the user does not give their consent, ads can be shown as long as no profiling has been carried out._**

---

Q3. Why is the GDPR message, configured on my AdMob console, not being displayed on my emulator? While the ATT works perfectly.
A3. https://stackoverflow.com/questions/73607714/why-is-my-google-admob-gdpr-consent-form-not-presented-in-my-ios-app

> Not really sure about this, will come here in a future if I do not get it displayed in production.

---

[You also don't have to avoid requests without consent. There is no penalty for requesting ads, as far as I'm aware, you just won't get any ads served.](https://github.com/birgernass/react-native-ad-consent/issues/23#issuecomment-1320361851)

**Comment by VictorioMolina** [comment]
Closing since following the current documentation for EEA-based users everything is OK (GDPR compliant).

**Comment by VictorioMolina** [comment]
I'm back again. Yes, the GDPR form will only be displayed when you set the payment config in AdMob Platform and they verify your account.

By the way, I am using this new config to determine whether personalizedAds should be rendered or not:

```
const handlePersonalizedAds = async () => {
    const choices = await AdsConsent.getUserChoices();

    const personalisedAds = choices.storeAndAccessInformationOnDevice &&
      choices.selectBasicAds &&
      choices.createAPersonalisedAdsProfile &&
      choices.selectPersonalisedAds &&
      choices.measureAdPerformance &&
      choices.applyMarketResearchToGenerateAudienceInsights &&
      choices.developAndImproveProducts;

    alert(`personalisedAds: ${personalisedAds}`);

    setShouldServePersonalizedAds(personalisedAds);
  };
```

[Source](https://stackoverflow.com/questions/63583003/admob-tcf-error-when-using-google-ump-sdk/64740925#64740925)

**Comment by mikehardy** [comment]
I'm not sure that tidbit about account payment info + verification seems pretty useful (as does the code + link) and I'm not sure our EU page has that - you are probably the most informed person now to say, could I beg for a quick edit (top right of the page I think? web based PR flow is pretty quick...) to the docs :pray: :pray:

**Comment by VictorioMolina** [comment]
@mikehardy yes its pretty useful. As soon (this week) as my lawyer verifies my implementation (to make sure its 100% GDPR compliant) I will update the docs, because I have had to take a look at different source codes of other apps and seem they do not require the necessary permissions.

**Comment by TaylorDale** [comment]
Whilst this isn't in scope of the repo, I figured may not hurt to ask people dealing with the same issue; With this becoming a mandatory requirement soon for EEA users - if the user selects the right options they can effectively get a completely free no-ads version of the app (From what I've read there are 3 levels of granularity based on user selections: Personalised ads, no-tracking limited ads, and no ads at all).

How are devs dealing with this? There is a lot of talk about it but I've never seen a structured approach (Both technically by analysing the user's returned consent variables, and then holistically as in what to do in-app when user denies all). Considering too that it appears on iOS we're not able to wall-off the app telling the user that to continue they must purchase the ads free version or reconsider their selections, for example (re https://developer.apple.com/app-store/review/guidelines/#3.2.2 )

Pretty confused - are we effectively forced to offer an unpaid, ad-free option in the EEA? 

See this multi-year, long-winded conversation with Google reps that shares the same concerns and also ultimately has no answer:
https://groups.google.com/g/google-admob-ads-sdk/c/UcveWmtBm4Q/m/moh9hvBVCwAJ

**Comment by mikehardy** [comment]
Hey @TaylorDale - interesting - I haven't been keeping up with the space. However, it seems like this part is the sticky one:

> (vi) Apps should allow a user to get what they’ve paid for without performing additional tasks, such as posting on social media, uploading contacts, checking in to the app a certain number of times, etc. Apps should not require users to rate the app, review the app, watch videos, download other apps, tap on advertisements, enable tracking, or take other similar actions in order to access functionality, content, use the app, or receive monetary or other compensation, including but not limited to gift cards and codes.

That indicates to me that you cannot require a user to repeatedly take actions just to use the app. However, I would argue that an ad-supported app may require users to at least enable non-personalized / complete-non-tracking ads in order to use functionality, and I think you could disable functionality until / unless they have done so. That's how I would structure my app though and the line I'd take with Apple anyway, to see if they approved it.

**Comment by TaylorDale** [comment]
> That indicates to me that you cannot require a user to repeatedly take actions just to use the app. However, I would argue that an ad-supported app may require users to at least enable non-personalized / complete-non-tracking ads in order to use functionality, and I think you could disable functionality until / unless they have done so. That's how I would structure my app though and the line I'd take with Apple anyway, to see if they approved it.

Yeah agreed, I think this is what I'll do. I'll tell you what Apple thinks of it soon, when I submit for review 😅

I'm surprised I'm not seeing this more widely talked about though, maybe it's just me but this seems like a pretty big deal/shakeup for EEA users.

**Comment by dylancom** [comment]
The UMP SDK has been updated as of yesterday:
https://developers.google.com/admob/ios/privacy/download
https://developers.google.com/admob/android/privacy/release-notes
"This release introduces several new APIs to simplify the consent gathering process."
Need to investigate this further though...

**Comment by TaylorDale** [comment]
Might have to create a separate issue for this but due to the combined EEA and ATT prompts the behaviour (for what I'd expect anyway) is different between iOS and Android and I'm not quite sure what to do about it when trying to implement the "block no-ads" feature.

*Android, non-EEA country*: Performs as expected, isConsentFormAvailable === false
*iOS, non-EEA country*: isConsentFormAvailable === true because ATT needs to display. However then I am stuck evaluating storeAndAccessInformationOnDevice, which will always be false in a non-EEA country (because the user will never get asked).


So unless I'm missing something here it's not possible to implement the deny-service to no ads users with the package at the moment if you want to use the ATT portion of UMP as well.

We need some way to interrogate if isConsentformAvailable is just for ATT purposes only, or both ATT and EEA in EEA countries.

Hopefully that makes sense - any advice?

**Comment by TaylorDale** [comment]
I've found AdsConsentPrivacyOptionsRequirementStatus which seems like this can do the job - If it's not required but consentform is available then we can deduce it's an ATT-only request.

However the typescript export for AdsConsentPrivacyOptionsRequirementStatus  is broken @mikehardy

**Comment by mikehardy** [comment]
We love PRs especially if you have direct experience with some broken but you've got an idea on how to fix...

**Comment by TaylorDale** [comment]
For sure - just for me to sum up my mess of a paragraph:

To implement an insufficient permissions for ads style page, for my purposes where UMP handles both EEA and ATT (Which I imagine is going to be a majority use case)

1. Ask user for consent if required
  consentInfo.status === AdsConsentStatus.REQUIRED   will be true if the user is in EEA *or* ATT is required *or* both.
2. Show UMP with AdsConsent.showForm()
  This will show EEA dialog, ATT dialog, or both depending on requirements
3. d
4. Check user answer with 
  AdsConsent.getUserChoices()
  
  If consentInfo.privacyOptionsRequirementStatus !== 'REQUIRED', move on to your app. Doing it in this order ensures ATT, if required, was requested, and then otherwise ignores EEA stuff if not required.
  
  If consentInfo.privacyOptionsRequirementStatus === 'REQUIRED', you are in EEA, then check userChoices.storeAndAccessInformationOnDevice === true. If it is, move on to app - you can show ads. If it's false, take user to EEA jail and ask them to reconsider ad choices and rerun the above logic, or buy the no-ads version


Hopefully that helps someone! 

I'd submit a pull request to fix the AdsConsentPrivacyOptionsRequirementStatus export but I'm not terribly familiar with maintaining public packages and I can do a dirty and use the string constant directly... sorry Mike.

**Comment by dylancom** [comment]
Please upgrade to 11.6.3 and it would be great if more people that are using this library would contribute 😄. I also started contributing (without prior library / native code experience) as I was using this package a lot.

**Comment by TaylorDale** [comment]
> Please upgrade to 11.6.3 and it would be great if more people that are using this library would contribute 😄. I also started contributing (without prior library / native code experience) as I was using this package a lot.

You guys are legends appreciate it very much. You'll see some pull requests from me some time soon I promise 🙌

**Comment by TaylorDale** [comment]
> @VictorioMolina Did you manage to show ads when the user select "manage choices"? Unless they choose to manually accept a lot of things (which they have no reasons to), it seems like no ads is shown, even if you ask for personnalized ads. It seems like for now, not clicking "accept all" means they won't be served ads.

User needs to select consent to store information only, then they will be shown ads.

I've implemented a system to take users to a paywall/reconsider and choices page if they deny storage consent and apple has passed it in their review, I mentioned it in the submission notes but honestly I doubt they took a look at it so we'll see if this is a long term solution.

**Comment by Pingou** [comment]
@TaylorDale Thank you for your answer. It was my understanding from this thread https://groups.google.com/g/google-admob-ads-sdk/c/UcveWmtBm4Q/m/moh9hvBVCwAJ that users needed to accept "storage", then accept "Google" from the giant list of vendors (non-alphabetical) to have ads shown, which I imagine virtually no user would ever do by himself.
I thought of your system but I'm sure a lot of users would just uninstall and (depending on your nice) would just install your competitor app, and that would be a bit hard to measure. On the other hand if you can't earn revenue from them I guess you don't lose that much anyway... Do you mind giving the name of your app so I can have a look at how you implemented it?

**Comment by koty2155** [comment]
Hi, I found out that if user give no consent for Purpose 1, you can still show limited ads (https://support.google.com/admob/answer/10105530?hl=en). If I understand this correctly library showing CMP form must use some framework [IAB TCF v2.0](https://iabeurope.eu/tcf-2-0/) to support these ads. Is it possible that this framework will included in this project in the future?

**Comment by drakulic-goran** [comment]
> @mikehardy I have been investigating, and [here](https://github.com/invertase/react-native-google-mobile-ads/issues/160) @wjaykim indicates that by using `AdsConsent.getUserChoices()` devs have to handle the Ads displaying.
> 
> I have followed the [official docs](https://docs.page/invertase/react-native-google-mobile-ads/european-user-consent):
> 
> 1. Create GDPR and ATT messages.
> 2. Request EEA consent when required and form available.
> 3. Inspect choices to decide if we should display ads or not.
> 
> I am getting exactly this same [issue](https://github.com/invertase/react-native-google-mobile-ads/issues/185), with the last version of this library.
> 
> 1. I get this warning when I call `AdsConsent.getUserChoices()`: _“Failed to decode tcString undefined: [TypeError: undefined is not an object (evaluating 'e.split')]”_.
> 2. On iOS emulator (not tested on physical device yet), I do not get the GDPR message displayed, only ATT. If this is happening to someone else, take a look at [this](https://stackoverflow.com/questions/73607714/why-is-my-google-admob-gdpr-consent-form-not-presented-in-my-ios-app). Might help.
> 
> I am very afraid of this warning, since it could be the reason that the user choices are always false. Any ideas?

I'm wondering if you managed to solve the problem with react-native-google-mobile-ads and GDPR message, where in __DEV_ mode adsConsent.getUserChoices() always returns user choices which are ALWAYS FALSE, even when I choose to consent to all in consent form that was presented to me without any problems, while AdsConsent.requestInfoUpdate() returns that user consent is already OBTAINED?
Will those user choices obtained from adsConsent.getUserChoices() be FALSE and in production and how to test whether they are adequate for personalized ads?

**Comment by akaoppa** [comment]
Since the 13th november my match rate dropped to almost 0. Anyone had this issue ?
![image](https://github.com/invertase/react-native-google-mobile-ads/assets/60573069/831f09de-3c88-42ca-8fe7-15f9243d5fb6)
