### ISSUE TITLE
[🐛] Bug Report Title - Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'RNGoogleMobileAdsModule' could not be found. Verify that a module by this name is registered in the native binary., js engine:

### ISSUE THREAD

**Issue by Bkind254** [invertase/react-native-google-mobile-ads#451]
### What happened?

Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'RNGoogleMobileAdsModule' could not be found. Verify that a module by this name is registered in the native binary., js engine: hermes

### Platforms

Only on Android

### React Native Info

```Shell
Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'RNGoogleMobileAdsModule' could not be found. Verify that a module by this name is registered in the native binary., js engine: hermes
```

### Are your using Typescript?

- [ ] My project is using Typescript

### package.json

```JSON
{
  "name": "test",
  "version": "1.0.0",
  "main": "node_modules/expo/AppEntry.js",
  "scripts": {
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "web": "expo start --web"
  },
  "dependencies": {
    "expo": "~49.0.10",
    "expo-status-bar": "~1.6.0",
    "react": "18.2.0",
    "react-native": "0.72.4",
    "react-native-google-mobile-ads": "^12.1.2"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0"
  },
  "private": true
}
```

### app.json

```JSON
{
  "expo": {
    "name": "test",
    "slug": "test",
    "version": "1.0.0",
    "orientation": "portrait",
    "icon": "./assets/da.png",
    "userInterfaceStyle": "light",
    "splash": {
      "image": "./assets/splash.png",
      "resizeMode": "contain",
      "backgroundColor": "#4caf50"
    },
    "assetBundlePatterns": ["**/*"],
    "ios": {
      "supportsTablet": true
    },
    "android": {
      "adaptiveIcon": {
        "foregroundImage": "./assets/adaptive-icon.png",
        "backgroundColor": "#ffffff"
      }
    },
    "web": {
      "favicon": "./assets/favicon.png"
    }
  },
  "react-native-google-mobile-ads": {
    "android_app_id": "ca-app-pub-7178411625478900389~9063717869"
  }
}
```

**Comment by Bkind254** [comment]
What do you mean authored a thread. How can i fix it?

**Comment by DoctorJohn** [comment]
@Bkind254 Your error message either means you're using Expo Go or you did not correctly rebuild your app and installed it.

We updated the Expo installation instruction, follow them (again) and you should be good to go.

Expo Go does not support custom native code, which this library heavily relies on. Expo dev clients are recommended as an more powerful alternative which works flawlessly with this library.

**Comment by usmanabid94** [comment]
I am still facing the same issue mentioned on react native 0.72.6 and 12.4.0
2023-11-29 15:51:08.620 27144-27291 ReactNativeJS                                   E  Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'RNGoogleMobileAdsModule' could not be found. Verify that a module by this name is registered in the native binary.

**Comment by usmanabid94** [comment]
is there any update on this?

**Comment by mikehardy** [comment]
@usmanabid94 this is an open source library, built by you - the developers of the library since open source implies there are no "users" we are developers - and all activity is conducted in the open. And I don't see any updates. Do you?

For anyone else following: if you don't see an update, there isn't one. If you really really need a question answered, you'll need to act like the developer of this module (because you are! it's open source!) and behave accordingly with code-level troubleshooting and a PR as needed.

If you can't do that work, you'll have to wait until someone that really needs it enough to dedicate their time to it does it for you. There is no guarantee this will ever happen, because it is open source. You'll have to decide how to allocate your development resources accordingly.

**Comment by skuxlife** [comment]
@usmanabid94 @demalmar Were y'all able to revisit the updated Expo installation instructions called out by @DoctorJohn? I was also seeing this error using EAS but creating another [development build](https://docs.expo.dev/develop/development-builds/create-a-build/) after implementing this package resolved the issue for me 👍

**Comment by usmanabid94** [comment]
> an easy way to fix it on expo GO:
> 
> ```
> import type { AdsConsentInterface } from "react-native-google-mobile-ads";
> 
> let AdsConsent: AdsConsentInterface | undefined = undefined;
> 
> if (isExpoGo) {
>     AdsConsent = require("react-native-google-mobile-ads").AdsConsent;
> }
> ```

@g3r4n Can you guide me how to do it in react native cli ?

**Comment by g3r4n** [comment]
@usmanabid94 replace the condition in the if by what you need to check to not load it during development. Maybe if(!__DEV__ ) could do the trick

**Comment by usmanabid94** [comment]
@g3r4n   i tried but invain i guess i have to wait or keep digging for it.

**Comment by g3r4n** [comment]
@usmanabid94 note that it won"t make it work, you'll just skip the errors and be able to develop on expo go or whatver you choose

**Comment by usmanabid94** [comment]
> @usmanabid94 note that it won"t make it work, you'll just skip the errors and be able to develop on expo go or whatver you choose

@g3r4n Thank you ☺️

**Comment by demalmar** [comment]
@g3r4n Hi, Could you please tell me from where or what is the variable "isExpoGo"? I have no clue and of course I'm getting a 
`ReferenceError: Property 'isExpoGo' doesn't exist`

**Comment by g3r4n** [comment]
It doesn't exist, it was just for the exemple. You need to create the value according to what you want

**Comment by usmanabid94** [comment]
@g3r4n I don,t know how but by just removing the build folder things are working fine now on react native cli.
Your contributions is still Thanked.:)

**Comment by stage88** [comment]
I managed to resolve this same issue by modifying my `MainApplication.java` file. 

I added this import statement:
`import io.invertase.googlemobileads.ReactNativeGoogleMobileAdsPackage;`

Then I updated the `getPackages` method to include `new ReactNativeGoogleMobileAdsPackage()` in the List of `ReactPackage`s that the method returns.

This line here in the error was probably a bit of a clue: `Verify that a module by this name is registered in the native binary`.

I haven't had time to spend diagnosing why I needed this step. For context, I get this error in Android only, when I run the app in Android Studio to execute on Android emulator.  I have a fairly old RN project and setup, but I am running on RN 72 and latest version of `react-native-google-mobile-ads`.

**Comment by mikehardy** [comment]
@stage88 that would only be required if your local react-native project has some sort of mis-integration that causes auto-linking to fail. RN72 should in all instances successfully auto-link react-native-google-mobile-ads I think, and no one should have to manually link the module in to their MainApplication (which is the sort of thing you had to do before auto-linking...)

**Comment by stage88** [comment]
@mikehardy totally is a fault of my own, having migrated this one particular RN project through various RN iterations, definitely missed one or two important steps so that auto-linking is not working properly

**Comment by bkvaiude** [comment]
For me, it was fixed after reinstalling the apps on the emulator and restarting the metro!

**Comment by paul-campbell-mgm** [comment]
> > an easy way to fix it on expo GO:
> > ```
> > import type { AdsConsentInterface } from "react-native-google-mobile-ads";
> > 
> > let AdsConsent: AdsConsentInterface | undefined = undefined;
> > 
> > if (isExpoGo) {
> >     AdsConsent = require("react-native-google-mobile-ads").AdsConsent;
> > }
> > ```
> 
> @g3r4n Can you guide me how to do it in react native cli ?

@g3r4n what file should this code block be in? I'm using the Platform export from react-native for isExpoGo

**Comment by alihandemirdas** [comment]
I'm still encountering this error. I am working with Expo Router in my project. I think the error comes from this. I'm not sure, but I have never encountered this error in my project where I did not use Expo Router.
"expo": "~52.0.20",
"react-native": "0.76.5"
"expo-router": "~4.0.15",

**Comment by mikehardy** [comment]
Huh - well first - this library doesn't support Expo Go, never has never will since they don't build the native code in there

Second - if this is expo-router specific that's unexpected, but either way, if it *is* Expo specific we'll need a motivated + interested person that is using it with Expo to post a PR. None of the maintainers are using Expo so we don't have experience here and will need help from the community

**Comment by ayush2034** [comment]
npm install react-native-google-mobile-ads@14.1.0

I am installing npm install react-native-google-mobile-ads@14.1.0 this specific package then my issue has resolved.

**Comment by sghsgm99** [comment]
I'm still encountering this error.
"expo": "~52.0.28",
"react-native": "0.76.6",
"expo-dev-client": "~5.0.11",
"expo-device": "~7.0.2",
"react-native-google-mobile-ads": "^14.8.1",

**Comment by mikehardy** [comment]
@sghsgm99 and your steps to reproduce are ... ?

Note that if your step to reproduce is `npx expo run` you're trying to use the Expo Go app, despite this being a native module that isn't included in Expo Go. So it'll never work as commented above. You'll need to prebuild etc

**Comment by sghsgm99** [comment]
-my environment
windows 11, node: 18.17.1, android studio: Koala Feature Drop 2024.1.2, eas-cli: 14.7.1, expo: 6.3.10
-step
app.json
{  
"expo": {
...
},
"react-native-google-mobile-ads": {
    "android_app_id": "ca-app-pub-7243252702136740~xxxxxxx"
  }
}

1. first method
npm start
open expo go in my emulator, then I can see error
` (NOBRIDGE) ERROR  Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'RNGoogleMobileAdsModule' could not be found. Verify that a module by this name is registered in the native binary. [Component Stack]`

2. 2nd method
npx expo prebuild
npx expo run:android
I can see error

![Image](https://github.com/user-attachments/assets/d87f9ecc-4c50-4b5f-bcd0-1c45db7d8b81)

![Image](https://github.com/user-attachments/assets/2cd26411-7441-47e7-9b77-303397d6f13c)

![Image](https://github.com/user-attachments/assets/fa4eb6ae-39e8-4332-80a8-94055f67782e)

![Image](https://github.com/user-attachments/assets/ac9ab1b7-d787-420b-a18b-dfd9f38e82c8)

**Comment by mikehardy** [comment]
@sghsgm99 - as you learned, using Expo Go without doing a local development build with prebuild etc will never work. The other thing you saw appears to be unrelated to this repo, something has gone wrong with your react-native-reanimated module integration

**Comment by sghsgm99** [comment]
@mikehardy , I fixed the issue. Thanks

**Comment by ceydamehves** [comment]
Facing the same issue (NOBRIDGE) ERROR Invariant Violation: TurboModuleRegistry.getEnforcing(...): 'RNGoogleMobileAdsModule' could not be found. Verify that a module by this name is registered in the native binary. [Component Stack]
-- **There is no problem when I install the packages, but when I want to use the admob code in index.jsx or any page, I get this error.**
**package.json:**
```
{
  "name": "beautyncare",
  "main": "expo-router/entry",
  "version": "1.0.0",
  "scripts": {
    "start": "expo start",
    "reset-project": "node ./scripts/reset-project.js",
    "android": "expo run:android",
    "ios": "expo run:ios",
    "web": "expo start --web",
    "test": "jest --watchAll",
    "lint": "expo lint"
  },
  "jest": {
    "preset": "jest-expo"
  },
  "dependencies": {
    "@expo/vector-icons": "^14.0.2",
    "@react-native-async-storage/async-storage": "^1.24.0",
    "@react-navigation/bottom-tabs": "^7.2.0",
    "@react-navigation/material-top-tabs": "^7.1.0",
    "@react-navigation/native": "^7.0.14",
    "@react-navigation/stack": "^7.1.1",
    "expo": "~52.0.32",
    "expo-blur": "~14.0.3",
    "expo-constants": "~17.0.5",
    "expo-dev-client": "~5.0.12",
    "expo-font": "~13.0.3",
    "expo-haptics": "~14.0.1",
    "expo-linking": "~7.0.5",
    "expo-router": "^4.0.17",
    "expo-splash-screen": "~0.29.21",
    "expo-status-bar": "~2.0.1",
    "expo-symbols": "~0.2.2",
    "expo-system-ui": "~4.0.8",
    "expo-web-browser": "~14.0.2",
    "firebase": "^11.3.1",
    "react": "18.3.1",
    "react-dom": "18.3.1",
    "react-native": "0.76.7",
    "react-native-gesture-handler": "~2.20.2",
    "react-native-google-mobile-ads": "^14.9.0",
    "react-native-pager-view": "^6.7.0",
    "react-native-reanimated": "~3.16.1",
    "react-native-safe-area-context": "^4.14.1",
    "react-native-screens": "~4.4.0",
    "react-native-tab-view": "^4.0.5",
    "react-native-vector-icons": "^10.2.0",
    "react-native-web": "~0.19.13",
    "react-native-webview": "13.12.5"
  },
  "devDependencies": {
    "@babel/core": "^7.25.2",
    "@types/jest": "^29.5.12",
    "@types/react": "~18.3.12",
    "@types/react-native": "^0.72.8",
    "@types/react-test-renderer": "^18.3.0",
    "jest": "^29.2.1",
    "jest-expo": "~52.0.3",
    "react-test-renderer": "18.3.1",
    "typescript": "^5.3.3"
  },
  "private": true
}
```

**Comment by sghsgm99** [comment]
@ceydamehves where did you try to have test?

**Comment by Developer-34** [comment]
> [@sghsgm99](https://github.com/sghsgm99) - as you learned, using Expo Go without doing a local development build with prebuild etc will never work. The other thing you saw appears to be unrelated to this repo, something has gone wrong with your react-native-reanimated module integration

I'm usinng react-native-cli still facing the same issue, please help me out, using  "react-native": "0.76.6"  and     "react-native-google-mobile-ads": "^15.3.1".

**Comment by TejasBitale** [comment]
Removing the caret (`^`) from the package version resolved this issue for me:

`"react-native-google-mobile-ads": "15.4.0" `

instead of 

`"react-native-google-mobile-ads": "^15.4.0"`

after changing this run `npm i `/ `yarn i` and rebuild the project.
