### ISSUE TITLE
[🐛] EAS build fails on IOS - PhaseScriptExecution ... (in target 'FBReactNativeSpec' from project 'Pods')

### ISSUE THREAD

**Issue by 3ddelano** [invertase/react-native-google-mobile-ads#526]
### What happened?

I'm trying to build on app with this ads package on EAS build. The android build works fine on EAS and ads show as expected. The issue is with IOS build on EAS gives an error.

I am only using the BannerAd. The code that shows the BannerAd is:
```javascript
import { Platform } from "react-native";
import { BannerAd, BannerAdSize } from "react-native-google-mobile-ads";

const ANDROID_AD_BANNER_ID = "XXXX";
const IOS_AD_BANNER_ID = "XXXX";

const AdBannerNative = () => {
  return (
      <BannerAd
        unitId={
          Platform.OS === "android" ? ANDROID_AD_BANNER_ID : IOS_AD_BANNER_ID
        }
        size={BannerAdSize.BANNER}
      />
  );
};

export default AdBannerNative;
```

The EAS build logs:
```
....lots of other logs
› Compiling react-native-safe-area-context Pods/react-native-safe-area-context » RNCSafeAreaContext.mm
› Compiling react-native Pods/React-RCTAppDelegate » React-RCTAppDelegate-dummy.m
› Compiling react-native Pods/React-RCTAppDelegate » RCTAppDelegate.mm
› Packaging react-native Pods/React-RCTAppDelegate » libReact-RCTAppDelegate.a
⚠️  Script has ambiguous dependencies causing it to run on every build.
   To fix, go to: Xcode » CPG/CPG » Build Phases » 'Start Packager'
   Either: Uncheck "Based on dependency analysis", or select output files to trigger the script
⚠️  Script has ambiguous dependencies causing it to run on every build.
   To fix, go to: Xcode » CPG/CPG » Build Phases » 'Bundle React Native code and images'
   Either: Uncheck "Based on dependency analysis", or select output files to trigger the script
⚠️  Script has ambiguous dependencies causing it to run on every build.
   To fix, go to: Xcode » CPG/CPG » Build Phases » '[CP-User] [RNGoogleMobileAds] Configuration'
   Either: Uncheck "Based on dependency analysis", or select output files to trigger the script
▸ ** ARCHIVE FAILED **
▸ The following build commands failed:
▸ 	PhaseScriptExecution [CP-User]\ Generate\ Specs /Users/expo/Library/Developer/Xcode/DerivedData/CPG-bfsbgwksqysqeefsehpmltyobbod/Build/Intermediates.noindex/ArchiveIntermediates/CPG/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/FBReactNativeSpec.build/Script-46EB2E000306D0.sh (in target 'FBReactNativeSpec' from project 'Pods')
▸ (1 failure)
** ARCHIVE FAILED **
The following build commands failed:
	PhaseScriptExecution [CP-User]\ Generate\ Specs /Users/expo/Library/Developer/Xcode/DerivedData/CPG-bfsbgwksqysqeefsehpmltyobbod/Build/Intermediates.noindex/ArchiveIntermediates/CPG/IntermediateBuildFilesPath/Pods.build/Release-iphoneos/FBReactNativeSpec.build/Script-46EB2E000306D0.sh (in target 'FBReactNativeSpec' from project 'Pods')
(1 failure)

Exit status: 65

+-------------+-------------------------+
|           Build environment           |
+-------------+-------------------------+
| xcode_path  | /Applications/Xcode.app |
| gym_version | 2.211.0                 |
| sdk         | iPhoneOS16.2.sdk        |
+-------------+-------------------------+
Looks like fastlane ran into a build/archive error with your project
It's hard to tell what's causing the error, so we wrote some guides on how
to troubleshoot build and signing issues: https://docs.fastlane.tools/codesigning/getting-started/
Before submitting an issue on GitHub, please follow the guide above and make
sure your project is set up correctly.
fastlane uses `xcodebuild` commands to generate your binary, you can see the
the full commands printed out in yellow in the above log.
Make sure to inspect the output above, as usually you'll find more error information there
[!] Error building the application - see the log above
Error: The "Run fastlane" step failed with an unknown error. Refer to "Xcode Logs" below for additional, more detailed logs.

```

### Platforms

Only on iOS

### React Native Info

```Shell
info Fetching system and libraries information...
System:
    OS: Windows 10 10.0.22621
    CPU: (8) x64 Intel(R) Core(TM) i5-9300H CPU @ 2.40GHz
    Memory: 7.29 GB / 15.87 GB
  Binaries:
    Node: 18.12.1 - C:\Program Files\nodejs\node.EXE
    Yarn: 3.3.1 - C:\Program Files\nodejs\yarn.CMD
    npm: 8.19.2 - C:\Program Files\nodejs\npm.CMD
    Watchman: Not Found
  SDKs:
    Android SDK:
      API Levels: 30, 33
      Build Tools: 29.0.3, 30.0.3, 33.0.0, 33.0.2
      System Images: android-33 | Google APIs Intel x86_64 Atom
      Android NDK: Not Found
    Windows SDK:
      AllowAllTrustedApps: Disabled
      AllowDevelopmentWithoutDevLicense: Disabled
      Versions: 10.0.19041.0
  IDEs:
    Android Studio: Not Found
    Visual Studio: 16.11.32126.315 (Visual Studio Community 2019)
  Languages:
    Java: 17.0.9 - C:\Program Files\Common Files\Oracle\Java\javapath\javac.EXE
  npmPackages:
    @react-native-community/cli: Not Found
    react: Not Found
    react-native: Not Found
    react-native-windows: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
```

### Are your using Typescript?

- [X] My project is using Typescript

### package.json

```JSON
{
  "name": "cpg-expo",
  "version": "0.0.0",
  "main": "index.js",
  "scripts": {
    "dev": "expo start",
    "devclient": "expo start --dev-client",
    "start": "expo start",
    "android": "expo start --android",
    "ios": "expo start --ios",
    "build:iosarchive": "eas build --profile iosarchive --platform ios"
  },
  "dependencies": {
    "@gorhom/bottom-sheet": "^4",
    "@react-native-async-storage/async-storage": "1.17.11",
    "@react-native-community/datetimepicker": "6.7.3",
    "@react-native-community/netinfo": "9.3.7",
    "@react-native-community/slider": "4.4.2",
    "@react-native-picker/picker": "2.4.8",
    "@react-navigation/bottom-tabs": "6.5.7",
    "@react-navigation/drawer": "^6.6.3",
    "@react-navigation/material-top-tabs": "6.6.2",
    "@react-navigation/native": "6.1.6",
    "@react-navigation/native-stack": "6.9.12",
    "@stripe/stripe-react-native": "0.23.3",
    "@supabase/supabase-js": "2.12.1",
    "@tanstack/react-query": "4.28.0",
    "@trpc/client": "10.37.1",
    "@trpc/react-query": "10.37.1",
    "@trpc/server": "10.37.1",
    "@types/react": "18.0.27",
    "bar-ads": "1.0.1",
    "base64-arraybuffer": "^1.0.2",
    "clsx": "^2.0.0",
    "dayjs": "^1.11.9",
    "expo": "48.0.0",
    "expo-av": "~13.2.1",
    "expo-build-properties": "~0.6.0",
    "expo-checkbox": "2.3.1",
    "expo-constants": "14.2.1",
    "expo-dev-client": "~2.2.1",
    "expo-image": "1.0.1",
    "expo-image-picker": "14.1.1",
    "expo-linear-gradient": "12.1.2",
    "expo-linking": "4.0.1",
    "expo-splash-screen": "0.18.2",
    "expo-status-bar": "1.4.4",
    "expo-updates": "0.16.4",
    "expo-web-browser": "~12.1.1",
    "nativewind": "^2.0.11",
    "react": "18.2.0",
    "react-native": "0.71.8",
    "react-native-alert-notification": "0.3.4",
    "react-native-gesture-handler": "2.9.0",
    "react-native-google-mobile-ads": "^12.10.0",
    "react-native-keyboard-aware-scroll-view": "0.9.5",
    "react-native-marked": "^6.0.2",
    "react-native-modal": "13.0.1",
    "react-native-pager-view": "6.1.2",
    "react-native-popup-menu": "0.16.1",
    "react-native-reanimated": "~2.14.4",
    "react-native-round-flags": "1.0.4",
    "react-native-safe-area-context": "4.5.0",
    "react-native-screens": "3.20.0",
    "react-native-svg": "13.4.0",
    "react-native-swiper-flatlist": "3.0.18",
    "react-native-tab-view": "3.5.1",
    "react-native-url-polyfill": "1.3.0",
    "react-native-util": "1.0.2",
    "superjson": "^1.13.1",
    "tailwind-merge": "^1.14.0",
    "typescript": "4.9.4",
    "uid": "^2.0.2",
    "use-debounce": "9.0.4"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@cpg/eslint-config": "*",
    "@typescript-eslint/eslint-plugin": "^5.59.6",
    "@typescript-eslint/parser": "^5.59.6",
    "babel-plugin-module-resolver": "^5.0.0",
    "eslint": "^8.41.0",
    "postcss": "^8.4.24",
    "react-native-svg-transformer": "^1.0.0",
    "tailwindcss": "3.3.2",
    "typescript": "^4.9.4"
  },
  "private": true,
  "eslintConfig": {
    "root": true,
    "extends": [
      "@cpg/eslint-config/base"
    ]
  }
}
```

### app.json

```JSON
{
  "expo": {
    "name": "CPG",
    "slug": "cpg-app",
    "scheme": "cpg",
    "version": "0.8.7",
    "orientation": "portrait",
    "icon": "./assets/adaptive-icon.png",
    "userInterfaceStyle": "dark",
    "splash": {
      "image": "./assets/icon.png",
      "resizeMode": "contain",
      "backgroundColor": "#1A1A1A"
    },
    "assetBundlePatterns": [
      "**/*"
    ],
    "ios": {
      "supportsTablet": true,
      "bundleIdentifier": "com.delanolourenco.cpgapp"
    },
    "android": {
      "adaptiveIcon": {
        "foregroundImage": "./assets/adaptive-icon.png",
        "backgroundColor": "#1A1A1A"
      },
      "package": "com.delanolourenco.cpg"
    },
    "extra": {
      "supabaseUrl": "[REDACTED FOR GITHUB]",
      "supabaseAnonKey": "[REDACTED FOR GITHUB]",
      "eas": {
        "projectId": "[REDACTED FOR GITHUB]"
      },
      "stripePublishableKey": "[REDACTED FOR GITHUB]"
    },
    "plugins": [
      [
        "expo-image-picker",
        {
          "photosPermission": "Allow the app to access your photos to upload an avatar, club icon, etc.",
          "cameraPermission": "Allow the app to access your camera to upload an avatar, club icon, etc."
        }
      ],
      [
        "@stripe/stripe-react-native",
        {
          "enableGooglePay": true
        }
      ]
    ],
    "runtimeVersion": {
      "policy": "appVersion"
    },
    "updates": {
      "url": "[REDACTED FOR GITHUB]"
    }
  },
  "react-native-google-mobile-ads": {
    "android_app_id": "ca-app-pub-XXXXX~XXXX",
    "ios_app_id": "ca-app-pub-XXXX~XXXX"
  }
}
```

**Comment by 3ddelano** [comment]
Issue is resolved after upgrading to Expo SDK 50

**Comment by FlawaCLV** [comment]
@3ddelano I'm still having this issue. I've tried every version with Expo SDK 50 and latest. Same for `react-native-google-mobile-ads` versions. Can't find the right configuration :/

**Comment by stefanatanasovmk** [comment]
I've just updated to Expo SDK 51 and this issue start showing when tried to build development build using `eas build`. Is there some update for this?

**Comment by 3ddelano** [comment]
I think the issue is it needs some very specific version of native libraries. I stopped using this package because the maintenance is too high.

**Comment by stefanatanasovmk** [comment]
After some time trying to fix the problem, I realized that I actually use a forked version of this package, because something else in the past was an issue that I needed to solve, dependencies are hell 😄 I fixed my issue by syncing my fork with the latest updates of this package.
