### ISSUE TITLE
Show Rate is extremely low

### ISSUE THREAD

**Issue by zoobibackups** [invertase/react-native-google-mobile-ads#542]
### What happened?

there is no issue when I test ads on test id. each and every thing works fine. but when our app is deployed the show rate is extremely low.  here is am showing the status of our apps.

any one can check this. I can provide more details for this upon asking.  I have used the same library in more than 15 projects. same issue on the all

![Screenshot 2](https://github.com/invertase/react-native-google-mobile-ads/assets/78194973/6cef6475-39cd-4590-ba74-64ec1f4f5d47)

### Platforms

Android and iOS

### React Native Info

```Shell
info Fetching system and libraries information...
System:
  OS: macOS 14.0
  CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
  Memory: 6.04 GB / 32.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 18.18.2
    path: ~/.nvm/versions/node/v18.18.2/bin/node
  Yarn:
    version: 1.22.19
    path: ~/.yarn/bin/yarn
  npm:
    version: 9.8.1
    path: ~/.nvm/versions/node/v18.18.2/bin/npm
  Watchman:
    version: 2023.12.04.00
    path: /usr/local/bin/watchman
Managers:
  CocoaPods:
    version: 1.12.0
    path: /Users/apple/.rbenv/shims/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.2
      - iOS 17.2
      - macOS 14.2
      - tvOS 17.2
      - visionOS 1.0
      - watchOS 10.2
  Android SDK:
    API Levels:
      - "25"
      - "28"
      - "29"
      - "30"
      - "31"
      - "32"
      - "33"
      - "34"
    Build Tools:
      - 19.1.0
      - 20.0.0
      - 21.1.2
      - 22.0.1
      - 23.0.1
      - 23.0.2
      - 23.0.3
      - 24.0.0
      - 24.0.1
      - 24.0.2
      - 24.0.3
      - 25.0.0
      - 25.0.1
      - 25.0.2
      - 25.0.3
      - 26.0.0
      - 26.0.1
      - 26.0.2
      - 26.0.3
      - 27.0.0
      - 27.0.1
      - 27.0.2
      - 27.0.3
      - 28.0.0
      - 28.0.1
      - 28.0.2
      - 28.0.3
      - 29.0.0
      - 29.0.1
      - 29.0.2
      - 29.0.3
      - 30.0.0
      - 30.0.1
      - 30.0.2
      - 30.0.3
      - 31.0.0
      - 32.0.0
      - 32.1.0
      - 33.0.0
      - 33.0.1
      - 33.0.2
      - 34.0.0
      - 34.0.0
      - 34.0.0
      - 34.0.0
      - 34.0.0
    System Images:
      - android-30 | Google Play Intel x86 Atom
    Android NDK: Not Found
IDEs:
  Android Studio: 2023.1 AI-231.9392.1.2311.11255304
  Xcode:
    version: 15.2/15C500b
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.9
    path: /usr/bin/javac
  Ruby:
    version: 2.7.5
    path: /Users/apple/.rbenv/shims/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.2.0
    wanted: 18.2.0
  react-native:
    installed: 0.72.4
    wanted: 0.72.4
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
```

### Are your using Typescript?

- [ ] My project is using Typescript

### package.json

```JSON
{
  "name": "TrueCaller",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "npx react-native run-ios --simulator='iPhone 15 Pro Max'",
    "lint": "eslint .",
    "start": "react-native start",
    "test": "jest"
  },
  "dependencies": {
    "@invertase/react-native-apple-authentication": "^2.2.2",
    "@react-native-async-storage/async-storage": "^1.19.3",
    "@react-native-community/blur": "^4.3.2",
    "@react-native-firebase/app": "^18.3.2",
    "@react-native-firebase/auth": "^18.3.2",
    "@react-native-firebase/messaging": "^18.3.2",
    "@react-native-google-signin/google-signin": "^10.0.1",
    "@react-native-masked-view/masked-view": "^0.2.9",
    "@react-navigation/bottom-tabs": "^6.5.8",
    "@react-navigation/drawer": "^6.6.3",
    "@react-navigation/native": "^6.1.7",
    "@react-navigation/native-stack": "^6.9.13",
    "@reduxjs/toolkit": "^1.9.5",
    "google-libphonenumber": "^3.2.33",
    "libphonenumbers": "^1.3.0",
    "lottie-react-native": "^6.2.0",
    "moment": "^2.29.4",
    "react": "18.2.0",
    "react-native": "0.72.4",
    "react-native-admob-native-ads": "^0.6.6",
    "react-native-contacts": "^7.0.7",
    "react-native-device-info": "^10.9.0",
    "react-native-easy-grid": "^0.2.2",
    "react-native-gesture-handler": "^2.12.1",
    "react-native-google-mobile-ads": "^12.1.1",
    "react-native-iap": "^12.10.7",
    "react-native-image-crop-picker": "^0.40.0",
    "react-native-largelist-v3": "^3.1.0-rc.1",
    "react-native-linear-gradient": "^2.8.3",
    "react-native-modal": "^13.0.1",
    "react-native-permissions": "^3.9.0",
    "react-native-popup-menu": "^0.16.1",
    "react-native-ratings": "^8.1.0",
    "react-native-reanimated": "^3.4.2",
    "react-native-responsive-fontsize": "^0.5.1",
    "react-native-responsive-screen": "^1.4.2",
    "react-native-safe-area-context": "^4.7.2",
    "react-native-screens": "^3.25.0",
    "react-native-share": "^9.4.1",
    "react-native-shimmer-placeholder": "^2.0.9",
    "react-native-size-matters": "^0.4.0",
    "react-native-splash-screen": "^3.3.0",
    "react-native-spring-scrollview": "^3.0.1-rc.1",
    "react-native-svg": "^13.13.0",
    "react-native-tab-view": "^3.5.2",
    "react-native-toast-message": "^2.1.6",
    "react-native-tracking-transparency": "^0.1.2",
    "react-native-vector-icons": "^10.0.0",
    "react-native-webview": "^13.5.1",
    "react-redux": "^8.1.2",
    "redux-persist": "^6.0.0"
  },
  "devDependencies": {
    "@babel/core": "^7.20.0",
    "@babel/preset-env": "^7.20.0",
    "@babel/runtime": "^7.20.0",
    "@react-native/eslint-config": "^0.72.2",
    "@react-native/metro-config": "^0.72.11",
    "@tsconfig/react-native": "^3.0.0",
    "@types/react": "^18.0.24",
    "@types/react-test-renderer": "^18.0.0",
    "babel-jest": "^29.2.1",
    "eslint": "^8.19.0",
    "jest": "^29.2.1",
    "metro-react-native-babel-preset": "0.76.8",
    "prettier": "^2.4.1",
    "react-native-svg-transformer": "^1.1.0",
    "react-test-renderer": "18.2.0",
    "typescript": "4.8.4"
  },
  "engines": {
    "node": ">=16"
  }
}
```

### app.json

```JSON
{
  "name": "MyApp",
  "displayName": "MyApp",
  "react-native-google-mobile-ads": {
    "android_app_id": "my.app.id",
    "ios_app_id": "my.app.id",
    "delay_app_measurement_init": true,
    "user_tracking_usage_description": "my app description",
    "sk_ad_network_items": [
      "cstr6suwn9.skadnetwork",
      "4fzdc2evr5.skadnetwork",
      "4pfyvq9l8r.skadnetwork",
      "2fnua5tdw4.skadnetwork",
      "ydx93a7ass.skadnetwork",
      "5a6flpkh64.skadnetwork",
      "p78axxw29g.skadnetwork",
      "v72qych5uu.skadnetwork",
      "ludvb6z3bs.skadnetwork",
      "cp8zw746q7.skadnetwork",
      "c6k4g5qg8m.skadnetwork",
      "s39g8k73mm.skadnetwork",
      "3qy4746246.skadnetwork",
      "3sh42y64q3.skadnetwork",
      "f38h382jlk.skadnetwork",
      "hs6bdukanm.skadnetwork",
      "prcb7njmu6.skadnetwork",
      "v4nxqhlyqp.skadnetwork",
      "wzmmz9fp6w.skadnetwork",
      "yclnxrl5pm.skadnetwork",
      "t38b2kh725.skadnetwork",
      "7ug5zh24hu.skadnetwork",
      "9rd848q2bz.skadnetwork",
      "y5ghdn5j9k.skadnetwork",
      "n6fk4nfna4.skadnetwork",
      "v9wttpbfk9.skadnetwork",
      "n38lu8286q.skadnetwork",
      "47vhws6wlr.skadnetwork",
      "kbd757ywx3.skadnetwork",
      "9t245vhmpl.skadnetwork",
      "a2p9lx4jpn.skadnetwork",
      "22mmun2rn5.skadnetwork",
      "4468km3ulz.skadnetwork",
      "2u9pt9hc89.skadnetwork",
      "8s468mfl3y.skadnetwork",
      "av6w8kgt66.skadnetwork",
      "klf5c3l5u5.skadnetwork",
      "ppxm28t8ap.skadnetwork",
      "424m5254lk.skadnetwork",
      "ecpz2srf59.skadnetwork",
      "uw77j35x4d.skadnetwork",
      "mlmmfzh3r3.skadnetwork",
      "578prtvx9j.skadnetwork",
      "4dzt52r2t5.skadnetwork",
      "gta9lk7p23.skadnetwork",
      "e5fvkxwrpn.skadnetwork",
      "8c4e2ghe7u.skadnetwork",
      "zq492l623r.skadnetwork",
      "3rd42ekr43.skadnetwork",
      "3qcr597p9d.skadnetwork"
    ]
  }
}
```

### ios/Podfile

```Ruby
# Resolve react_native_pods.rb with node to allow for hoisting
def node_require(script)
  # Resolve script with node to allow for hoisting
  require Pod::Executable.execute_command('node', ['-p',
    "require.resolve(
      '#{script}',
      {paths: [process.argv[1]]},
  )", __dir__]).strip
end

node_require('react-native/scripts/react_native_pods.rb')
node_require('react-native-permissions/scripts/setup.rb')
platform :ios, min_ios_version_supported
prepare_react_native_project!

setup_permissions([
  'AppTrackingTransparency',
  'Camera',
  'Contacts',
  'Notifications',
  'PhotoLibrary',
  'PhotoLibraryAddOnly',
])
flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled
linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

pod 'Google-Mobile-Ads-SDK',"10.9.0"
#pod 'GoogleMobileAdsMediationFacebook','6.11.0.0'

target 'TrueCaller' do
  config = use_native_modules!
  use_frameworks! :linkage => :static
  $RNFirebaseAsStaticFramework = true
  $RNGoogleMobileAdsAsStaticFramework = true
  $RNAdMobAsStaticFramework = true
  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default. Disable by setting this flag to false.
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    #:flipper_configuration => flipper_config,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'TrueCallerTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
```

### android/build.gradle

```Groovy
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext {
        buildToolsVersion = "33.0.0"
        minSdkVersion = 21
        compileSdkVersion = 33
        targetSdkVersion = 33

        // We use NDK 23 which has both M1 support and is the side-by-side NDK version from AGP.
        ndkVersion = "23.1.7779620"
        supportLibVersion = "28.0.0"
        
        // android X
        // androidXAnnotation = "1.1.0"
        // androidXBrowser = "1.0.0"
        // minSdkVersion = 24
        // kotlinVersion = "1.8.0"
    }
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath("com.android.tools.build:gradle")
        classpath("com.facebook.react:react-native-gradle-plugin")
        //classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion"
    }
}
```

### android/app/build.gradle

```Groovy
apply plugin: "com.android.application"
apply plugin: "com.facebook.react"

/**
 * This is the configuration block to customize your React Native Android app.
 * By default you don't need to apply any configuration, just uncomment the lines you need.
 */
react {
    /* Folders */
    //   The root of your project, i.e. where "package.json" lives. Default is '..'
    // root = file("../")
    //   The folder where the react-native NPM package is. Default is ../node_modules/react-native
    // reactNativeDir = file("../node_modules/react-native")
    //   The folder where the react-native Codegen package is. Default is ../node_modules/@react-native/codegen
    // codegenDir = file("../node_modules/@react-native/codegen")
    //   The cli.js file which is the React Native CLI entrypoint. Default is ../node_modules/react-native/cli.js
    // cliFile = file("../node_modules/react-native/cli.js")

    /* Variants */
    //   The list of variants to that are debuggable. For those we're going to
    //   skip the bundling of the JS bundle and the assets. By default is just 'debug'.
    //   If you add flavors like lite, prod, etc. you'll have to list your debuggableVariants.
    // debuggableVariants = ["liteDebug", "prodDebug"]

    /* Bundling */
    //   A list containing the node command and its flags. Default is just 'node'.
    // nodeExecutableAndArgs = ["node"]
    //
    //   The command to run when bundling. By default is 'bundle'
    // bundleCommand = "ram-bundle"
    //
    //   The path to the CLI configuration file. Default is empty.
    // bundleConfig = file(../rn-cli.config.js)
    //
    //   The name of the generated asset file containing your JS bundle
    // bundleAssetName = "MyApplication.android.bundle"
    //
    //   The entry file for bundle generation. Default is 'index.android.js' or 'index.js'
    // entryFile = file("../js/MyApplication.android.js")
    //
    //   A list of extra flags to pass to the 'bundle' commands.
    //   See https://github.com/react-native-community/cli/blob/main/docs/commands.md#bundle
    // extraPackagerArgs = []

    /* Hermes Commands */
    //   The hermes compiler command to run. By default it is 'hermesc'
    // hermesCommand = "$rootDir/my-custom-hermesc/bin/hermesc"
    //
    //   The list of flags to pass to the Hermes compiler. By default is "-O", "-output-source-map"
    // hermesFlags = ["-O", "-output-source-map"]
}

/**
 * Set this to true to Run Proguard on Release builds to minify the Java bytecode.
 */
def enableProguardInReleaseBuilds = false

/**
 * The preferred build flavor of JavaScriptCore (JSC)
 *
 * For example, to use the international variant, you can use:
 * `def jscFlavor = 'org.webkit:android-jsc-intl:+'`
 *
 * The international variant includes ICU i18n library and necessary data
 * allowing to use e.g. `Date.toLocaleString` and `String.localeCompare` that
 * give correct results when using with locales other than en-US. Note that
 * this variant is about 6MiB larger per architecture than default.
 */
def jscFlavor = 'org.webkit:android-jsc:+'

android {
    ndkVersion rootProject.ext.ndkVersion

    compileSdkVersion rootProject.ext.compileSdkVersion

    namespace "com.truecaller"
    defaultConfig {
        applicationId "com.truecaller"
        missingDimensionStrategy "store", "play"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 1
        versionName "1.0"
    }
    signingConfigs {
        debug {
            storeFile file('debug.keystore')
            storePassword 'android'
            keyAlias 'androiddebugkey'
            keyPassword 'android'
        }
    }
    buildTypes {
        debug {
            signingConfig signingConfigs.debug
        }
        release {
            // Caution! In production, you need to generate your own keystore file.
            // see https://reactnative.dev/docs/signed-apk-android.
            signingConfig signingConfigs.debug
            minifyEnabled enableProguardInReleaseBuilds
            proguardFiles getDefaultProguardFile("proguard-android.txt"), "proguard-rules.pro"
        }
    }
}

dependencies {
    // The version of react-native is set by the React Native Gradle Plugin
    implementation("com.facebook.react:react-android")

    debugImplementation("com.facebook.flipper:flipper:${FLIPPER_VERSION}")
    debugImplementation("com.facebook.flipper:flipper-network-plugin:${FLIPPER_VERSION}") {
        exclude group:'com.squareup.okhttp3', module:'okhttp'
    }

    debugImplementation("com.facebook.flipper:flipper-fresco-plugin:${FLIPPER_VERSION}")
    if (hermesEnabled.toBoolean()) {
        implementation("com.facebook.react:hermes-android")
    } else {
        implementation jscFlavor
    }
}

apply from: file("../../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesAppBuildGradle(project)
apply from: file("../../node_modules/react-native-vector-icons/fonts.gradle")
```

### android/settings.gradle

```Groovy
rootProject.name = 'MyApp'
apply from: file("../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesSettingsGradle(settings)
include ':app'
includeBuild('../node_modules/@react-native/gradle-plugin')
```

### AndroidManifest.xml

```XML
<manifest
xmlns:tools="http://schemas.android.com/tools"
xmlns:android="http://schemas.android.com/apk/res/android"
>

    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
    <uses-permission android:name="android.permission.DOWNLOAD_WITHOUT_NOTIFICATION" />
    <uses-permission android:name="android.permission.READ_MEDIA_IMAGES" />
    <uses-permission android:name="android.permission.READ_MEDIA_VIDEO" />
    <uses-permission android:name="android.permission.RECEIVE_BOOT_COMPLETED"/>
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.READ_CONTACTS" />
    <uses-permission android:name="android.permission.WRITE_CONTACTS" />

    <application
      android:name=".MainApplication"
      android:label="@string/app_name"
      android:icon="@mipmap/ic_launcher"
      android:roundIcon="@mipmap/ic_launcher_round"
      android:allowBackup="false"
      android:networkSecurityConfig="@xml/network_security_config"
      android:theme="@style/AppTheme">
      <activity
        android:name=".MainActivity"
        android:label="@string/app_name"
        android:configChanges="keyboard|keyboardHidden|orientation|screenLayout|screenSize|smallestScreenSize|uiMode"
        android:launchMode="singleTask"
        android:windowSoftInputMode="adjustResize"
        android:exported="true">
        <intent-filter>
            <action android:name="android.intent.action.MAIN" />
            <category android:name="android.intent.category.LAUNCHER" />
        </intent-filter>
      </activity>
      <activity
        android:name="com.google.android.gms.ads.AdActivity"
        android:theme="@style/AdTheme"
        tools:replace="android:theme"
      />
      <meta-data
        tools:replace="android:value"
        android:name="com.google.android.gms.ads.APPLICATION_ID"
        android:value="ca-app-pub-3940256099942544~3347511713"
      />
    </application>
</manifest>
```

**Comment by dylancom** [comment]
It's your app open ads that have a low show rate...
I guess this is normal or you should check your implementation.
If you request an app open ad... there is no guarantee that the user will re-open your app within 4 hours and thus if an app open ad can be shown at all.
For more info check out the official admob docs about "app open ads".

**Comment by AftabUfaq** [comment]
@dylancom i have the same issue. 

i have attached the images. the show rate is extremely low in all apps
![Screenshot 3](https://github.com/invertase/react-native-google-mobile-ads/assets/34965107/fa418cbc-0039-4bf0-a231-795da2d39a1c)
![Screenshot 2024-02-06 033127](https://github.com/invertase/react-native-google-mobile-ads/assets/34965107/d4b80ec7-f89a-4f4b-bcad-e0c446abba4b)

**Comment by dylancom** [comment]
We do nothing more special here than just making available the Google Mobile Ads SDK methods to React Native. For in depth questions about why your show rate is low etc. please head over to the official forums: https://groups.google.com/g/google-admob-ads-sdk

**Comment by AftabUfaq** [comment]
i have implemented ads in android it has a good show rate of above 80 but on react-native the show rate is extremely low. i have implemented it in more then 10 apps. i can also pay for it if someone here can review my code or implementation here.  @dylancom @zoobibackups @mikehardy @Ehesp @amolrajoba

**Comment by dylancom** [comment]
Tagging @DoctorJohn here, he could help on a contract basis.

**Comment by birdofpreyru** [comment]
Thanks @dylancom :wave: 

@AftabUfaq looking at your screenshots, I see you have a great match rate of 97% &mdash; I actually have just ~45% across my apps as of recently, and still not sure why, whether it is due to things outside of my control, or some bugs in my logic (it used to be ~90% up to the end of last year, and I haven't change much anything related to the ads since). So... low show rate kind of feels to me that it is just you not showing the ads when you can, or perhaps reloading them more often then you actually need it.

**Comment by AftabUfaq** [comment]
@birdofpreyru i have used this simple implementation on the android side. 

```
import { useEffect, useState } from 'react';
import { AdEventType, InterstitialAd } from 'react-native-google-mobile-ads';
import Config from '../../env';
export function useAppOpenAd() {

  const [ad_closed, setAdClosed] = useState(false);
  const [loading, setLoading] = useState(true);
  
  const  interstitialAd = InterstitialAd.createForAdRequest(Config.INTER_SPLASH, {
    requestNonPersonalizedAdsOnly: true,
  });
  
  useEffect(() => {
    const adEventListener1 = interstitialAd.addAdEventsListener(
      ({type, payload}) => {
        if (type === AdEventType.ERROR) {
          setLoading(false);
        }
        if (type === AdEventType.LOADED) {
          interstitialAd.show();
        }
        if (type === AdEventType.CLOSED) {
          setAdClosed(true);
        }
      },
    );

   
    interstitialAd.load();
    
    return() => {
      interstitialAd.removeAllListeners(adEventListener1)
    }
  }, []);


  useEffect(() => {
    interstitialAd.load();
  }, []);
  
  return {
    ad_closed,
    loading,
  };
}
```
App.js file 


```
import React from 'react';
import Geolocation from 'react-native-geolocation-service';
import SplashScreen from 'react-native-splash-screen';
import Toast from 'react-native-toast-message';
import {Provider} from 'react-redux';
import {PersistGate} from 'redux-persist/integration/react';
import MainApp from './src/navigation';
import {persistor, store} from './src/store/index';
import {useAppOpenAd} from './src/hooks/appopenAdhook';
import {useEffect} from 'react';
Geolocation.setRNConfiguration({
  config: {
    skipPermissionRequests: true,
    authorizationLevel: 'auto',
    locationProvider: 'auto',
  },
});
const App = () => {
  const {
    ad_closed,
    loading,    
  } = useAppOpenAd();
  useEffect(() => {
    if (ad_closed) {
      SplashScreen.hide();
    }
    if (!loading) {
      SplashScreen.hide();
    }
  }, [ad_closed, loading])

  
  return (
    <Provider store={store}>
      <PersistGate loading={null} persistor={persistor} onBeforeLift={() => {}}>
        <MainApp />
      </PersistGate>
      <Toast />
    </Provider>
  );
};

export default App;
```


here is my calculation for this.    


![1](https://github.com/invertase/react-native-google-mobile-ads/assets/34965107/c8238cef-023d-484d-a742-3f7114f8a0cf)

**Comment by AftabUfaq** [comment]
@birdofpreyru @dylancom can we check my implemenation here

**Comment by birdofpreyru** [comment]
With just a brief look at your code @AftabUfaq , I don't see anything special about it. I wouldn't do
```tsx
const  interstitialAd = InterstitialAd.createForAdRequest(Config.INTER_SPLASH, {
    requestNonPersonalizedAdsOnly: true,
  });
```
in the place you do, because in a more complex app it would fire on each re-render of the component using the hook.

Anyway, I am currently busy with another project, thus not much interested in looking into it.

**Comment by radekzz** [comment]
Without any change in my apps, today i have show rate 0% but i see the ads in the apps, so it's probably some issue in AdMob?

**Comment by AftabUfaq** [comment]
> Without any change in my apps, today i have show rate 0% but i see the ads in the apps, so it's probably some issue in AdMob?

can you show how you implemented ads in the app . we can start a standard example app where their is best ads implementation possible.

**Comment by radekzz** [comment]
@AftabUfaq currently i have 2 different implementations that vary through my apps
https://github.com/invertase/react-native-google-mobile-ads/issues/510#issuecomment-1966300079

I have to say, that showrate got back, but still significantly lower

**Comment by AftabUfaq** [comment]
@radekzz @zoobibackups i have another issuw with this is that i have created build and all ads were working. after 12 to 12 hours suddenly no ads were showing in the app. after clearing data of the app ads start working again.

**Comment by radekzz** [comment]
My ads revived somehow without any action from my side. However show rate is 75% although I have match rate 100%.
I'm afraid we cannot do much here as I have ads managed completely by Google.

**Comment by AftabUfaq** [comment]
> My ads revived somehow without any action from my side. However show rate is 75% although I have match rate 100%. I'm afraid we cannot do much here as I have ads managed completely by Google.

can you share how you integrated interstial  ads.

**Comment by Jamal-Ud-Din-hub** [comment]
@zoobibackups @AftabUfaq @dylancom @radekzz @birdofpreyru 

Everything works fine in **debug mode**, but no interstitial or app open is show in release mode. I am using iOS only.

<img width="1000" alt="Image" src="https://github.com/user-attachments/assets/82b6ee03-f233-4eda-a95c-905592e12641" />

I used **@react-native-admob/admob** in other apps 

<img width="985" alt="Image" src="https://github.com/user-attachments/assets/74c10575-4b7e-4c63-b64b-688a3ec96066" />

**@react-native-admob/admob** has one of the best ads implementation, just compare the results.

**Comment by dylancom** [comment]
@Jamal-Ud-Din-hub same underlying SDK, the creator even works on this lib and ported functionalities from it into this.

**Comment by Jamal-Ud-Din-hub** [comment]
> [@Jamal-Ud-Din-hub](https://github.com/Jamal-Ud-Din-hub) same underlying SDK, the creator even works on this lib and ported functionalities from it into this.

@dylancom thanks for your response, i'm not sure about the issue but i'm still using that deprecated package and the results are awesome, everything works exactly the same in production app as they are working in debug mode. As per my observation and experience the ads **match / show rate are 100%** using both test and live Ad ids respectively.
